package pump

import (
	genericAPIServer "github.com/pachirode/iam_study/internal/pkg/server"
	"github.com/pachirode/iam_study/internal/pump/config"
	"github.com/pachirode/iam_study/internal/pump/options"
	"github.com/pachirode/iam_study/pkg/app"
	"github.com/pachirode/iam_study/pkg/log"
)

const commandDesc = `IAM Pump is a pluggable analytics purger to move Analytics generated by your iam nodes to any back-end`

func NewApp(basename string) *app.App {
	opts := options.NewOptions()
	application := app.NewApp("IAM analytics server",
		basename,
		app.WithOptions(opts),
		app.WithDescription(commandDesc),
		app.WithDefaultValidArgs(),
		app.WithRunFunc(run(opts)),
	)

	return application
}

func run(opts *options.Options) app.RunFunc {
	return func(basename string) error {
		log.Init(opts.Log)
		defer log.Flush()

		cfg, err := config.CreateConfigFromOptions(opts)
		if err != nil {
			return err
		}

		stopCh := genericAPIServer.SetupSignalHandler()

		return Run(cfg, stopCh)
	}
}
